### PR TITLE
Fix no viable overloaded '*=' error on HIP vectors

### LINKED ISSUE #527: `make build_tests`fails
... on the latest main with an error:
```
$ make build_tests
...
[100%] Building CXX object catch/catch_tests/unit/texture/CMakeFiles/hipTextureObj1DCheckSRGBModes.dir/hipTextureObj1DCheckSRGBModes.cc.o
In file included from /mnt/md1/linehill/ws-chip-spv-2/chip-spv/HIP/tests/catch/unit/texture/hipTextureObj1DCheckSRGBModes.cc:20:
In file included from /mnt/md1/linehill/ws-chip-spv-2/chip-spv/HIP/tests/catch/./include/hip_test_common.hh:24:
In file included from /mnt/md1/linehill/ws-chip-spv-2/chip-spv/HIP/tests/catch/./include/hip_test_context.hh:24:
In file included from /mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/hip_runtime.h:73:
In file included from /mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/spirv_hip_runtime.h:43:
In file included from /mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/hip_runtime_api.h:510:
In file included from /mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/texture_types.h:55:
In file included from /mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/channel_descriptor.h:44:
In file included from /mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/spirv_channel_descriptor.h:30:
/mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/spirv_hip_vector_types.h:616:35: error: no viable overloaded '*='
  return HIP_vector_type<T, n>{x} *= y;
         ~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~
/mnt/md1/linehill/ws-chip-spv-2/chip-spv/HIP/tests/catch/./include/hip_texture_helper.hh:246:22: note: in instantiation of function template specialization 'operator*<float, 4U, float>' requested here
      return (1 - a) * t1 + a * t2;
                     ^
/mnt/md1/linehill/ws-chip-spv-2/chip-spv/HIP/tests/catch/unit/texture/hipTextureObj1DCheckSRGBModes.cc:143:9: note: in instantiation of function template specialization 'getExpectedValue<HIP_vector_type<float, 4>, hipAddressModeClamp, hipFilterModePoint, false>' requested here
        getExpectedValue<float4, addressMode, filterMode, sRGB>(width, offsetX + j, hInputData);
        ^
/mnt/md1/linehill/ws-chip-spv-2/chip-spv/HIP/tests/catch/unit/texture/hipTextureObj1DCheckSRGBModes.cc:180:5: note: in instantiation of function template specialization 'runTest<hipAddressModeClamp, hipFilterModePoint, hipResourceTypeArray, false, false>' requested here
    runTest<hipAddressModeClamp, hipFilterModePoint, hipResourceTypeArray, false>(255, -3.9);
    ^
/mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/spirv_hip_vector_types.h:489:36: note: candidate template ignored: requirement 'std::is_convertible<HIP_vector_type<float, 4>, float>{}' was not satisfied [with U = HIP_vector_type<float, 4>]
  __HOST_DEVICE__ HIP_vector_type &operator*=(U x) noexcept {
 ...
```
The issue was probably introduced by d5885164394ceb07667a2000bf8fb9d843a2ea46 ("Fix 513"). If I checkout a commit prior it, then the command succeeds. The [unit-tests-llvm-15-debug](https://github.com/CHIP-SPV/chipStar/actions/runs/5437565685/jobs/9888543111) checker also saw the same issue:
```
2023-07-02T20:41:41.8181645Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/HIP/tests/catch/unit/texture/hipTextureObj2DCheckSRGBModes.cc:20:
2023-07-02T20:41:41.8182517Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/HIP/tests/catch/./include/hip_test_common.hh:24:
2023-07-02T20:41:41.8183286Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/HIP/tests/catch/./include/hip_test_context.hh:24:
2023-07-02T20:41:41.8184175Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/build/include/hip/hip_runtime.h:73:
2023-07-02T20:41:41.8184898Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/build/include/hip/spirv_hip_runtime.h:43:
2023-07-02T20:41:41.8185498Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/build/include/hip/hip_runtime_api.h:510:
2023-07-02T20:41:41.8890978Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/build/include/hip/texture_types.h:55:
2023-07-02T20:41:41.8891520Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/build/include/hip/channel_descriptor.h:44:
2023-07-02T20:41:41.8892016Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/build/include/hip/spirv_channel_descriptor.h:30:
2023-07-02T20:41:41.8892208Z 
2023-07-02T20:41:42.2440653Z /home/pvelesko/actions-runner/_work/chipStar/chipStar/build/include/hip/spirv_hip_vector_types.h:616:35: error: no viable overloaded '*='
2023-07-02T20:41:42.2440990Z 
2023-07-02T20:41:42.2441409Z   return HIP_vector_type<T, n>{x} *= y;
2023-07-02T20:41:42.2441794Z          ~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~
...
```

### PR DESCRIPTION
**Pull request by linehill**
* Fix HIP samples and tests were not recompiled if HIP headers were modified or updated after `git pull` (the ones under include/hip and HIP/include/hip under the source tree). The compilation relied on HIP headers that were copied to build directory with `file(COPY ...)` command which is only executed once after initial configuration.
* Fix no viable overloaded '*=' error on HIP vectors. Only uncommented a region that was commented out in #513 but the changes didn't propagated before the above fix.

Fixes #527.

### CODE REVIEW

**Comment by pvelesko** [comment]
Have you been able to figure out why clang-16 works fine and 15 fails to compile?

**Comment by pvelesko** [comment]
You can ignore the failing test - I have a fix in the immediate command list branch but that's currently blocked by a regression in the driver.

**Comment by linehill** [comment]
> Have you been able to figure out why clang-16 works fine and 15 fails to compile?

Perhaps due to the first bullet point in the PR description - HIP header changes didn't get propagated forward causing misleading errors.

**Comment by pvelesko** [comment]
How is that related to clang 15 vs clang 16? 

The CI process builds everything from scratch starting with git pull

**Comment by pjaaskel** [comment]
Confirmed that this fixes the LLVM 16 build_tests here. I suggest to pull this in since the main is now broken for LLVM 16 (and I'm wondering why the CI didn't catch the breakage).

**Comment by pvelesko** [comment]
Llvm 16 was fine it was llvm15 that was failing to compile and the CI didn't fail because the tests that failed to compile were already excluded and CI isn't set to auto fail if a compilation error is encountered

**Comment by pjaaskel** [comment]
I just tested here with LLVM 16 and it failed to build the tests with the above error without Henry's PR.
