### ISSUE TITLE
macOS: MathsTest fails to compile in the device pass, aborting build_tests

### ISSUE THREAD

**Issue by Noerr** [CHIP-SPV/chipStar#1583]
`make build_tests` cannot complete on macOS: the `MathsTest` target fails to compile. All
of the remaining errors are emitted **by the device pass** (`N errors generated when
compiling for spirv64v1.3-unknown-chipstar`), not the host pass.

Filing this in chipStar rather than hip-tests because most of it is about what chipStar's
devicelib provides, and because two of the four groups need a policy decision rather than a
patch.

### Practical impact: it hides ~190 passing tests

`make build_tests` stops at the first failing target, so nothing after `MathsTest` gets
built and `scripts/check.py` then reports a large number of spurious `Not Run` results:

| | tests run | reported |
|---|---|---|
| after `make build_tests` | 187 | 86% (26 failures, mostly `Not Run`) |
| after `make -k build_tests` | 378 | 98% (7 real failures) |

So the macOS test picture looks far worse than it is. Whatever happens to the rest of this
issue, `-k` in the docs/CI invocation would help.

### Group 1 — `std::min` type deduction (10 sites) — already fixed

Mixing `size_t` and `uint64_t` in `std::min`, which cannot deduce where those are spelled
differently (Darwin, and any ILP32 target). PR: CHIP-SPV/hip-tests#2. Not part of this
issue; listed only because you have to fix it to see the rest.

### Group 2 — `long double` reaching the device pass (15 errors)

`root_funcs.cc:125` writes a host reference in `long double`:

```cpp
auto rsqrt_ref = [](long double arg) -> long double { return 1.L / std::sqrt(arg); };
```

In the device pass the only `sqrt` candidates are chipStar's:

```
error: call to 'sqrt' is ambiguous
note: candidate function  include/hip/devicelib/half/half_math.hh:39
        extern __device__ api_half sqrt(api_half x);
note: candidate function  include/hip/devicelib/double_precision/dp_math.hh:479
        static inline __device__ double sqrt(double x);
```

There is no `long double` overload, so neither candidate is an exact match and the call is
ambiguous. Note `std::sqrt` reaches these because `dp_math.hh:527-557` does
`namespace std { using ::sqrt; ... }`, and `int_math.hh:117-122` does the same for `abs` —
both with a comment explaining that Clang's HIP wrappers don't compile on chipStar.

The same shape produces the 6 `abs` errors, via `boost::math::ccmath::abs<double>` calling
unqualified `abs(x)` and finding only chipStar's integer overloads.

This resolves cleanly on the host, so it is specific to the device pass. A minimal
host-only reproduction of the `using ::sqrt` hoisting compiles fine.

`long double` is also 8 bytes with a 53-bit mantissa on arm64 Darwin (vs 16 bytes / 64-bit
on x86_64 Linux), so `long double` references are not buying extra precision here anyway.

**Question for maintainers:** should devicelib grow `long double` overloads (aliasing
`double` where the target has no wider type), or should these host-only reference lambdas
be kept out of the device pass, or should hip-tests use `double` for references?

### Group 3 — libc++ has no C++17 special math (4 errors)

```
error: no member named 'cyl_bessel_i' in namespace 'std'
```

`special_funcs.cc` uses `std::cyl_bessel_i`. libc++ does not implement the C++17
mathematical special functions — there are zero occurrences of `cyl_bessel_i` in upstream
`libcxx/include/cmath` on `main`. libstdc++ does implement them, which is why this is
invisible on typical Linux builds.

Not fixable in hip-tests without either vendoring an implementation or excluding these
tests where the standard library lacks them. That is a policy call.

### Group 4 — glibc-only libm functions (7 errors)

```
error: use of undeclared identifier 'j0l'   (also j1l, jnl, y0l, y1l, ynl)
error: address of overloaded function 'exp10' cannot be static_cast to type 'double (*)(double)'
```

- The long-double Bessel functions `j0l`/`j1l`/`jnl`/`y0l`/`y1l`/`ynl` are glibc
  extensions. macOS `math.h` has the `double` forms (`j0`, `j1`, `jn`) but none of the
  `long double` ones.
- `exp10` is likewise a glibc extension; macOS spells it `__exp10` / `__exp10f`.

Both need a portability shim or a guard, and both interact with Group 2 — on arm64 Darwin
`long double` is `double`, so the `l` variants could reasonably forward to the `double`
ones.

### Environment

- macOS 26.6.2, Apple Silicon (M4); Xcode 26.6 (SDK 26.5, `_LIBCPP_VERSION 210106`)
- LLVM 23.1.0-rc2 (`561093d9`), translator variant, built via `scripts/configure_llvm.sh --version 23`
- chipStar `main` @ `8f44c604`, hip-tests @ `83deaba3` (`develop-chipstar`)
- Homebrew boost at `/opt/homebrew/include/boost`

Happy to take a patch for Group 4, and for Group 2 once you say which direction you prefer.

**Comment by Noerr** [comment]
Retested on macOS with #1584 in. Thank you — the `long double` half of this is essentially
gone.

Measured on macOS 26.6.2 / Apple Silicon, SDK 26.5, LLVM 23.1.0-rc2, PoCL `main`, comparing
chipStar `8f44c604` against `9ad35e7c`, with CHIP-SPV/hip-tests#2 applied so the `std::min`
errors do not mask the rest:

| Group | error | before | after |
|---|---|---|---|
| 2 | `call to 'abs' is ambiguous` | 6 | **0** |
| 2 | `call to 'sqrt' is ambiguous` | 9 | **1** |
| 3 | `no member named 'cyl_bessel_i'` | 4 | 4 |
| 4 | `j0l`/`j1l`/`jnl`/`y0l`/`y1l`/`ynl` undeclared | 6 | 6 |
| 4 | `exp10` static_cast | 1 | 1 |

(Group 1 was the `std::min` deduction failure, fixed separately in
CHIP-SPV/hip-tests#2 and applied here so it does not mask the rest.)

Groups 3 and 4 are unchanged as expected — those were the two I flagged as policy calls
rather than patches, and I did not read #1584 as claiming them.

### The one surviving `sqrt`

`special_funcs.cc:349` — and it is **not** a regression from #1584; it was in the pre-#1584
failure set too. It is a different sub-case: the argument is an *integer*, not a
`long double`.

```cpp
auto normcdf_ref = [](double arg) -> double { return std::erfc(-arg / std::sqrt(2)) / 2; };
//                                                                          ^ int literal
```

```
error: call to 'sqrt' is ambiguous
note: candidate function  devicelib/half/half_math.hh:39            api_half sqrt(api_half)
note: candidate function  devicelib/double_precision/dp_math.hh:479 double   sqrt(double)
```

`[c.math.fp]` requires "sufficient additional overloads" so that a call with an integral
argument resolves to the `double` form; libc++ provides them, devicelib does not, so `int`
converts equally well to more than one candidate. A constrained integral overload
forwarding to `double` would close it, in the same shape as the `long double` forwarding
#1584 added:

```cpp
template <class T, class = std::enable_if_t<std::is_integral_v<T>>>
__device__ inline double sqrt(T x) { return sqrt(static_cast<double>(x)); }
```

But, it is worth deciding first whether it belongs on every hoisted function or only where
tests hit it — the same shape would apply
to `erfc`, `pow` and friends the moment a test passes them an `int`.

I have not touched Groups 3 and 4 pending your call on direction.
