### ISSUE TITLE
OpenCL: __syncthreads_and/__syncthreads_or unresolved (__chip_group_all not linked) — regression 2026.06.25 -> 2026.07.20

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chipStar#1359]
Any kernel using __syncthreads_and/__syncthreads_or fails to JIT on current main (worked on 2026.06.25 install, fails on 2026.07.20). Build log: 'No rtdevlib imports, building directly' then 'error: unresolved external symbol __chip_group_all'. chipStar reports hipErrorNotInitialized (Program build failed) at CHIPBackendOpenCL.cc:1268:compile.

Root cause: the group-collectives device library providing __chip_group_all is not detected as an rtdevlib import, so it is never linked.

Secondary defect: the build error is not propagated — hipDeviceSynchronize returns hipSuccess and the program continues with the kernel never run (HeCBench nms-hip completes with 'Detections after NMS: 0').

Repro: any kernel calling __syncthreads_and(1), CHIP_BE=opencl. Found via HeCBench nms-hip. Arc B570.
