### ISSUE TITLE
`make build_tests`fails

### ISSUE THREAD

**Issue by linehill** [CHIP-SPV/chipStar#527]
... on the latest main with an error:
```
$ make build_tests
...
[100%] Building CXX object catch/catch_tests/unit/texture/CMakeFiles/hipTextureObj1DCheckSRGBModes.dir/hipTextureObj1DCheckSRGBModes.cc.o
In file included from /mnt/md1/linehill/ws-chip-spv-2/chip-spv/HIP/tests/catch/unit/texture/hipTextureObj1DCheckSRGBModes.cc:20:
In file included from /mnt/md1/linehill/ws-chip-spv-2/chip-spv/HIP/tests/catch/./include/hip_test_common.hh:24:
In file included from /mnt/md1/linehill/ws-chip-spv-2/chip-spv/HIP/tests/catch/./include/hip_test_context.hh:24:
In file included from /mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/hip_runtime.h:73:
In file included from /mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/spirv_hip_runtime.h:43:
In file included from /mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/hip_runtime_api.h:510:
In file included from /mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/texture_types.h:55:
In file included from /mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/channel_descriptor.h:44:
In file included from /mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/spirv_channel_descriptor.h:30:
/mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/spirv_hip_vector_types.h:616:35: error: no viable overloaded '*='
  return HIP_vector_type<T, n>{x} *= y;
         ~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~
/mnt/md1/linehill/ws-chip-spv-2/chip-spv/HIP/tests/catch/./include/hip_texture_helper.hh:246:22: note: in instantiation of function template specialization 'operator*<float, 4U, float>' requested here
      return (1 - a) * t1 + a * t2;
                     ^
/mnt/md1/linehill/ws-chip-spv-2/chip-spv/HIP/tests/catch/unit/texture/hipTextureObj1DCheckSRGBModes.cc:143:9: note: in instantiation of function template specialization 'getExpectedValue<HIP_vector_type<float, 4>, hipAddressModeClamp, hipFilterModePoint, false>' requested here
        getExpectedValue<float4, addressMode, filterMode, sRGB>(width, offsetX + j, hInputData);
        ^
/mnt/md1/linehill/ws-chip-spv-2/chip-spv/HIP/tests/catch/unit/texture/hipTextureObj1DCheckSRGBModes.cc:180:5: note: in instantiation of function template specialization 'runTest<hipAddressModeClamp, hipFilterModePoint, hipResourceTypeArray, false, false>' requested here
    runTest<hipAddressModeClamp, hipFilterModePoint, hipResourceTypeArray, false>(255, -3.9);
    ^
/mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/spirv_hip_vector_types.h:489:36: note: candidate template ignored: requirement 'std::is_convertible<HIP_vector_type<float, 4>, float>{}' was not satisfied [with U = HIP_vector_type<float, 4>]
  __HOST_DEVICE__ HIP_vector_type &operator*=(U x) noexcept {
 ...
```
The issue was probably introduced by d5885164394ceb07667a2000bf8fb9d843a2ea46 ("Fix 513"). If I checkout a commit prior it, then the command succeeds. The [unit-tests-llvm-15-debug](https://github.com/CHIP-SPV/chipStar/actions/runs/5437565685/jobs/9888543111) checker also saw the same issue:
```
2023-07-02T20:41:41.8181645Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/HIP/tests/catch/unit/texture/hipTextureObj2DCheckSRGBModes.cc:20:
2023-07-02T20:41:41.8182517Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/HIP/tests/catch/./include/hip_test_common.hh:24:
2023-07-02T20:41:41.8183286Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/HIP/tests/catch/./include/hip_test_context.hh:24:
2023-07-02T20:41:41.8184175Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/build/include/hip/hip_runtime.h:73:
2023-07-02T20:41:41.8184898Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/build/include/hip/spirv_hip_runtime.h:43:
2023-07-02T20:41:41.8185498Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/build/include/hip/hip_runtime_api.h:510:
2023-07-02T20:41:41.8890978Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/build/include/hip/texture_types.h:55:
2023-07-02T20:41:41.8891520Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/build/include/hip/channel_descriptor.h:44:
2023-07-02T20:41:41.8892016Z In file included from /home/pvelesko/actions-runner/_work/chipStar/chipStar/build/include/hip/spirv_channel_descriptor.h:30:
2023-07-02T20:41:41.8892208Z 
2023-07-02T20:41:42.2440653Z /home/pvelesko/actions-runner/_work/chipStar/chipStar/build/include/hip/spirv_hip_vector_types.h:616:35: error: no viable overloaded '*='
2023-07-02T20:41:42.2440990Z 
2023-07-02T20:41:42.2441409Z   return HIP_vector_type<T, n>{x} *= y;
2023-07-02T20:41:42.2441794Z          ~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~
...
```

**Comment by pvelesko** [comment]
strange that only clang15 fails - the tests that failed to build are already excluded so I missed that. 

In that PR I updated the `spirv_hip_vector_types.h` from hipamd - I can rollback that change.

**Comment by pvelesko** [comment]
Any clue on why the compilation fails for clang-15? It would be nice to find out and use the more recent version of the file. @pjaaskel

**Comment by pjaaskel** [comment]
@linehill  can you check this?

**Comment by linehill** [comment]
> @linehill can you check this?

Sure.
